---
title: "Exploration Transition 8"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

<!-- Learn more about flexdashboard at https://rstudio.github.io/flexdashboard -->


```{r load pkgs, include=FALSE}
# Application
library(flexdashboard)
library(shiny)

# Data wrangling
library(readr)
library(dplyr)
library(tidyr)

# Plots
library(ggplot2)
library(gridExtra)
library(ggthemes)

# Tables
library(xtable)
library(knitr)
library(formattable) # devtools::install_github("renkun-ken/formattable")

# Interactive Plots
library(parcoords) # devtools::install_github("timelyportfolio/parcoords")


# Spatial
library(sp)
```

```{r load files, include = FALSE}
basePath <- "../GAMA/transition8/outputs/"
currExperiment <- "base2_compo5_2quat"
parameters_file <- sprintf("%s%s_parameters_TMD.csv", basePath, currExperiment)
global_file <- sprintf("%s%s_results_TMD.csv", basePath, currExperiment)
seigneurs_file <- sprintf("%s%s_results_TMD_seigneurs.csv", basePath, currExperiment)
agregats_file <- sprintf("%s%s_results_TMD_agregats.csv", basePath, currExperiment)
poles_file <- sprintf("%s%s_results_TMD_poles.csv", basePath, currExperiment)
paroisses_file <- sprintf("%s%s_results_TMD_paroisses.csv", basePath, currExperiment)
fullFP_file <- sprintf("%s%s_results_TMD_FP_all.csv", basePath, currExperiment)
summFP_file <- sprintf("%s%s_results_TMD_summFP.csv", basePath, currExperiment)

parameters_raw <- read_csv(file = parameters_file, col_names = FALSE)
global_raw <- read_csv(file = global_file, col_names = FALSE)
seigneurs_raw <- read_csv(file = seigneurs_file, col_names = FALSE)
agregats_raw <- read_csv(file = agregats_file, col_names = FALSE)
poles_raw <- read_csv(file = poles_file, col_names = FALSE)
paroisses_raw <- read_csv(file = paroisses_file, col_names = FALSE)
fullFP_raw <- read_csv(file = fullFP_file, col_names = FALSE)
summFP_raw <- read_csv(file = summFP_file, col_names = FALSE)
```

```{r set colnames, include = FALSE}

colnames(parameters_raw) <- c("myseed", "debut_simulation", "fin_simulation", "duree_step", "besoin_protection", "distance_detection_agregats", "nombre_FP_agregat", "nombre_agglos_antiques", "nombre_villages", "nombre_foyers_villages_max", "puissance_communautes", "apparition_communautes", "proba_apparition_communaute", "nombre_foyers_paysans", "taux_renouvellement", "taux_mobilite", "distance_max_dem_local", "seuil_puissance_armee", "deplacement_alternate", "nombre_seigneurs_objectif", "nombre_grands_seigneurs", "nombre_petits_seigneurs", "puissance_grand_seigneur1", "puissance_grand_seigneur2", "proba_collecter_loyer", "proba_creation_ZP_banaux", "proba_creation_ZP_basseMoyenneJustice", "rayon_min_PS", "rayon_max_PS", "min_fourchette_loyers_PS", "max_fourchette_loyers_PS", "proba_don_partie_ZP", "apparition_chateaux", "nb_chateaux_potentiels_GS", "seuil_attractivite_chateau", "proba_creer_chateau_GS", "proba_chateau_agregat", "proba_don_chateau_GS", "proba_creer_chateau_PS", "proba_gain_droits_hauteJustice_chateau", "proba_gain_droits_banaux_chateau", "proba_gain_droits_basseMoyenneJustice_chateau", "proba_promotion_groschateau_multipole", "proba_promotion_groschateau_autre", "puissance_necessaire_creation_chateau_GS", "puissance_necessaire_creation_chateau_PS", "nombre_eglises", "nb_eglises_paroissiales", "proba_gain_droits_paroissiaux", "nb_max_paroissiens", "nb_min_paroissiens", "ratio_paroissiens_agregats", "nb_paroissiens_mecontents_necessaires", "attrac_0_eglises", "attrac_1_eglises", "attrac_2_eglises", "attrac_3_eglises", "attrac_4_eglises", "attrac_GC", "attrac_PC", "attrac_communautes", "chateaux_GS_alternate", "chateaux_PS_alternate", "puissance_armee_FP_alternate", "communautes_attractives")

colnames(global_raw) <- c("Seed", "Annee", "NbChateaux", "NbGrosChateaux", "NbEglises", "NbEglisesParoissiales", "DistPpvEglises", "DistPpvEglisesParoissiales", "TxFpIsoles", "ChargeFiscale", "DistPpvFpAgregat", "Duree")

colnames(seigneurs_raw) <- c("Seed", "Annee", "IdSeigneur", "Type", "Initial", "Puissance", "NbChateauxProprio", "NbChateauxGardien", "NbFpAssujetis", "NbVassaux", "NbDebiteurs")

colnames(agregats_raw) <- c("Seed", "Annee", "IdAgregat", "NbFpContenus", "NbFpContenusAvantDem", "NbFpAttires", "Surface", "Communaute","Geom")

colnames(poles_raw) <- c("Seed", "Annee", "IdPole", "Attractivité", "NbAttracteurs", "Agregat","NbEglises", "NbParoisses", "NbGC", "NbPC", "NbCA", "Geom")

colnames(paroisses_raw) <- c("Seed", "Annee", "IdParoisse", "Eglise", "Superficie", "NbFideles", "Satisfaction", "Geom")

colnames(fullFP_raw) <- c("Seed", "Annee", "nbInInIntra", "nbInOutIntra", "nbOutInIntra", "nbOutOutIntra", "nbInInInter", "nbInOutInter", "nbOutInInter", "nbOutOutInter")

colnames(summFP_raw) <- c("Seed", "Annee", "NbDeplacementLocaux", "NbDeplacementLointains", "NbSat25inf", "NbSat25-49", "NbSat50-75", "NbSat75+")
```

```{r wrangle data, include = FALSE}
poles_raw <- poles_raw %>%
  mutate(Geom = gsub(x = Geom, pattern = "{", replacement="", perl = TRUE)) %>%
  mutate(Geom = gsub(x = Geom, pattern = "}", replacement="", perl = TRUE)) %>%
  separate(Geom, into=c("X", "Y", "Z"), sep = ",") %>%
  mutate_each(funs(as.numeric), X,Y,Z) %>%
  select(-Z)

agregats_raw <- agregats_raw %>%
  mutate(Geom = gsub(x = Geom, pattern = "{", replacement="", perl = TRUE)) %>%
  mutate(Geom = gsub(x = Geom, pattern = "}", replacement="", perl = TRUE)) %>%
  separate(Geom, into=c("X", "Y", "Z"), sep = ",") %>%
  mutate_each(funs(as.numeric), X,Y,Z) %>%
  select(-Z) %>%
  mutate(Communaute = as.logical(Communaute))

seigneurs_raw <- seigneurs_raw %>%
  mutate(Initial = as.logical(Initial))

global_raw <- global_raw %>%
  inner_join({
    agregats_raw %>%
      group_by(Seed, Annee) %>%
      summarise(NbAgregats = n())
             },
    by=c("Seed", "Annee")
    ) %>%
  inner_join({
    filter(., Annee == 820) %>%
      mutate(CFinit = ChargeFiscale) %>%
      select(Seed, CFinit)
  }, by="Seed") %>%
  mutate(RatioChargeFiscale = ChargeFiscale / CFinit) %>%
  select(-CFinit)
```

```{r reactive filtered datasets, include = FALSE}
goodSeeds <- reactive({
  fullFP_raw %>%
    group_by(Seed) %>%
    summarise(Complet = n_distinct(Annee)) %>%
    filter(Complet == 18) %>%
    select(Seed) %>%
    unlist(use.names = FALSE) %>%
    sample(size = input$nbReplications)
})

global_data <- reactive(global_raw %>% filter(Seed %in% goodSeeds())) 
seigneurs_data <- reactive(seigneurs_raw %>% filter(Seed %in% goodSeeds())) 
agregats_data <- reactive(agregats_raw %>% filter(Seed %in% goodSeeds())) 
poles_data <- reactive(poles_raw %>% filter(Seed %in% goodSeeds())) 
paroisses_data <- reactive(paroisses_raw %>% filter(Seed %in% goodSeeds())) 
fullFP_data <- reactive(fullFP_raw %>% filter(Seed %in% goodSeeds())) 
summFP_data <- reactive(summFP_raw %>% filter(Seed %in% goodSeeds())) 
```


Settings {.sidebar}
=====================================

```{r}
sliderInput("nbReplications", 
            label = "Nb de réplications à analyser",
             min = 5, max = 50, value = 20)
```

Objectifs et Paramètres
=====================================  

Column
-------------------------------------
    
### Tableau des objectifs
    
```{r summary table, include = FALSE}
ecarts_types <- reactive({
  global_data() %>%
    filter(Annee == 1160) %>%
  select(NbAgregats,NbChateaux, NbGrosChateaux, NbEglisesParoissiales, DistPpvEglises, TxFpIsoles,RatioChargeFiscale) %>%
  sapply(sd, simplify = TRUE)
})

summary_table <- reactive({
  global_data() %>%
    filter(Annee == 1160) %>%
    select(NbAgregats,NbChateaux, NbGrosChateaux, NbEglisesParoissiales, DistPpvEglises, TxFpIsoles,RatioChargeFiscale) %>%
    summary() %>%
    as.data.frame(stringsAsFactors = FALSE) %>%
    select(Var2, Freq) %>%
    separate(Freq,  into = c("Indice", "Valeur"),  sep = ":") %>%
    mutate(Valeur = as.numeric(Valeur)) %>%
    spread(Indice, Valeur) %>%
   
    rename(Indice = Var2, Q1 = `1st Qu.`, Q3 = `3rd Qu.`, Max = `Max.   `, Min = `Min.   `, Moyenne = `Mean   `, `Médiane` = `Median `) %>%
    mutate(StDev = as.numeric(ecarts_types())) %>%
    arrange(order(names(ecarts_types()))) %>%
    mutate(Objectif = c(200, 50, 10, 300, 3000, 0.2, 3)) %>%
    mutate(Ecart = (Moyenne / Objectif) -  1 ) %>%
    select(Indice, Objectif,Moyenne, Ecart, `Médiane`, Q1, Q3, StDev, Min, Max) %>%
    mutate(Indice = c("Nombre d'agrégats", "Nombre de châteaux",  "Nombre de gros châteaux",
                      "Nombre d'églises paroissiales", "Distance moyenne entre églises",  
                      "Proportion de FP isolés", "Augmentation de la charge fiscale (ratio)"))
})

```

```{r print summary}
renderFormattable({
  
  arrondir <- formatter("span", 
  style = function(x) style(round(x, digits = 2)))
  
  formattable(summary_table(), list(
      Objectif = formatter("span", style = function(x){as.integer(x)}),
      Moyenne = arrondir,
      Ecart = formatter("span", style = function(x){
        ifelse(abs(x) > 0.3,  style(color = "red", font.weight = "bold"),
               ifelse(abs(x) < 0.1, style(color = "green", font.weight = "bold"), NA))},
        function(x) percent(x)),
      `Médiane` = arrondir,
      Q1 = arrondir,
      Q3 = arrondir,
      StDev = formatter("span", style = function(x) style(round(x, digits = 2))),
      Min = formatter("span", style = function(x){as.integer(x)}),
      Max = formatter("span", style = function(x){as.integer(x)})
      
))
})
```

```


### Chart 2

```{r}

```


Seigneurs
=====================================     

### Chart 2
    
```{r}
```

Châteaux
=====================================     

### Chart 2
    
```{r}
renderText({
  input$blob
})
```
